spring:
  application:
    name: gateway-server
  messages:
    basename: vi
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  elasticsearch:
    uris: http://localhost:9200
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      httpclient:
        pool:
          max-connections: 500
          acquireTimeout: 10000
      routes:
        #SERVER
        - id: auth-server
          uri: http://localhost:7001
          predicates:
            - Path=/auth-server/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10

        #SERVICE
        - id: auth-command
          uri: http://localhost:8001
          predicates:
            - Path=/auth-command/**
          filters:
            - StripPrefix=1
        - id: auth-query
          uri: http://localhost:8003
          predicates:
            - Path=/auth-query/**
          filters:
            - StripPrefix=1
server:
  port: 7000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

base:
  environment:
    debug: true
