spring:
  application:
    name: gateway-server
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 7000


logging:
  level:
    org:
      springframework:
        security: debug

jwt:
  secret:
    key: ${jwtSecretKey}

henry:
  auth-query:
    api: localhost:8003

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:7002/eureka/
