spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7001/issuer
  application:
    name: gateway-server
  messages:
    basename: vi
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  elasticsearch:
    uris: http://localhost:9200
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      httpclient:
        pool:
          max-connections: 500
          acquireTimeout: 10000
      routes:
        #SERVICE
        - id: auth-command
          uri: http://localhost:8001
          predicates:
            - Path=/auth-command/**
          filters:
            - StripPrefix=1
        - id: auth-query
          uri: http://localhost:8003
          predicates:
            - Path=/auth-query/**
          filters:
            - StripPrefix=1
server:
  port: 7000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

base:
  jwt:
    internal-key: 0076274cba6f9d492a1e8b9c483648468f6baa0cb85b0b6e7f8b712be14c1ddf
    secret-key: 832c44b8a1935544ae6265c15261825468078fc965312afa74945edab0051bea
    expiration: 900000
