spring:
  messages:
    basename: vi
  main:
    allow-bean-definition-overriding: true
  application:
    name: auth-server
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: auth_event
    open-in-view: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/base-event?currentSchema=auth_event
    username: base
    password: 123456
  elasticsearch:
    uris: http://localhost:9200
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 7001
base:
  environment:
    debug: true
  jwt:
    secret-key: 832c44b8a1935544ae6265c15261825468078fc965312afa74945edab0051bea
    expiration: 900000
grpc:
  client:
    auth-query:
      address: static://localhost:8013
      negotiation-type: PLAINTEXT

