spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: notification-server
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: notification_event
    open-in-view: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DOCKER_POSTGRES_URL}/henry-event?currentSchema=notification_event
    username: ${DOCKER_POSTGRES_USERNAME}
    password: ${DOCKER_POSTGRES_PASSWORD}
server:
  port: 7003

environment:
  debug: true
prefix:
  api: ${PREFIX_SERVER}

henry:




