spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: notification-server
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: notification_event
    open-in-view: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/henry-event?currentSchema=notification_event
    username: henry
    password: 123456
server:
  port: 7003

prefix:
  api: ${prefixServer}

environment:
  debug: ${debug}

henry:




